# Generated by Django 6.1 on 2026-08-10 08:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RehabilitationEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='ENROLLED', max_length=50)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('attendance_rate', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RehabilitationProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('program_type', models.CharField(choices=[('DIGITAL_LITERACY', 'Digital Literacy'), ('COMPUTER_BASICS', 'Computer Basics'), ('COMMUNICATION_SKILLS', 'Communication Skills'), ('VOCATIONAL', 'Vocational Training'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('EDUCATION', 'Education'), ('LIFE_SKILLS', 'Life Skills')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('provider_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
