# Generated by Django 6.1 on 2026-08-10 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rehab', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rehabilitationenrollment',
            name='managed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rehabilitationenrollment',
            name='undertrial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehab_enrollments', to='users.undertrialprofile'),
        ),
        migrations.AddField(
            model_name='rehabilitationenrollment',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='rehab.rehabilitationprogram'),
        ),
    ]
