# Generated by Django 6.1 on 2026-08-10 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_aid', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('simple_explanation', models.TextField()),
                ('detailed_explanation', models.TextField()),
                ('who_can_help', models.CharField(blank=True, max_length=255, null=True)),
                ('what_to_do_next', models.TextField(blank=True, null=True)),
                ('required_documents', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
