# Generated by Django 6.1 on 2026-08-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rehabilitationprogram',
            name='program_type',
            field=models.CharField(choices=[('DIGITAL_LITERACY', 'Digital Literacy'), ('COMPUTER_BASICS', 'Computer Basics'), ('COMMUNICATION_SKILLS', 'Communication Skills'), ('VOCATIONAL', 'Vocational Training'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('EDUCATION', 'Education'), ('LIFE_SKILLS', 'Life Skills'), ('COUNSELING', 'Mental Health & Counseling'), ('LEGAL_LITERACY', 'Legal Rights Education')], max_length=50),
        ),
    ]
