# Generated by Django 6.1 on 2026-08-10 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='undertrial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='users.undertrialprofile'),
        ),
        migrations.AddField(
            model_name='case',
            name='utrc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='users.utrc'),
        ),
        migrations.AddField(
            model_name='bailapplication',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bail_applications', to='cases.case'),
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.court'),
        ),
        migrations.AddField(
            model_name='document',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hearing',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.court'),
        ),
    ]
